linters:
  disable-all: true
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocognit
    - gocritic
    - gocyclo
    - gofmt
    - gofumpt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  funlen:
    lines: 80
    statements: 55
  gocognit:
    min-complexity: 37

issues:
  exclude-rules:
    # prevent errors on //noinspection tags
    - linters:
        - gocritic
        - gofumpt
      source: "^\\s*//noinspection(?:[^\n]+)?$"
    # prevent errors on type assertions with field access
    - linters:
        - errorlint
      source: \w\.\(\*?\w+\)\.\w+
    - linters:
        - lll
      source: //(?:nolint|go|goland)
    # io.EOF and sql.ErrNoRows should, by doc, never be wrapped
    - linters:
        - errorlint
      source: "\\w+\\s*==\\s*(io.EOF|sql.ErrNoRows)"
    - path: (?:_test|test_util)\.go$
      linters:
        - bodyclose
        - dupl
        - errcheck
        - errorlint
        - funlen
        - gocognit
        - goconst
        - gocyclo
        - gosec
        - unparam
