linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - golint
    - stylecheck
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - gofmt
    - goimports
    - maligned
    - depguard
    - misspell
    - lll
    - unparam
    - dogsled
    - prealloc
    - gocritic
    - gochecknoinits
    - funlen

linters-settings:
  funlen:
    lines: 75
    statements: 50

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
        - goconst
        - funlen
        - maligned
    # test utilities might not fulfill all conventions, as they are just used
    # for testing
    - path: test_util\.go$
      linters:
        - golint
        - unparam
    # handling is pretty similar
    - path: ^pkg/errors/.+_error.go$
      linters: dupl
    # not a duplicate, but two types with delegate methods
    - path: ^pkg/errors/user_(info|error).go$
      linters: dupl
    # parsers are long...
    - path: ^pkg/impl/arg/.+_parser.go$
      linters:
       - funlen
       - gocognit
    # consistency with newArgParsingErr2
    - path: ^pkg/impl/arg/utils.go$
      linters: unparam
      text: "`newArgParsingErr` - `placeholders` always receives `nil`"
    # Text and AlphanumericID are not duplicates, parsing is just similar
    - path: ^pkg/impl/arg/text_types.go$
      linters: dupl
    # slight variations of the same logic
    - path: ^pkg/impl/arg/time_types.go$
      linters: dupl
    # restriction functions tend to get long/complex
    - path: ^pkg/impl/restriction/
      linters:
        - funlen
        - gocognit
    # resolving inheritance, not complicated, just long
    - path: ^pkg/plugin/registered_(command|module).go$
      linters:
        - funlen
        - gocognit
    # there would be no point in splitting this up
    - path: ^pkg/utils/embedutil/builder.go$
      linters: funlen
      text: ^Function 'Build' is too long \(\d+ > \d+\)$
    # part of type switch; can't be replaced
    - path: ^pkg/utils/messageutil/utils.go$
      linters: dupl
      text: ^\d+-\d+ lines are duplicate of `pkg/utils/messageutil/utils.go:\d+-\d+`$
    # no point in splitting up
    - path: ^pkg/utils/messageutil/reaction_waiter.go$
      linters: gocognit
      text: ^cognitive complexity \d+ of func `\(\*ReactionWaiter\).handleReactions` is high \(> \d+\)$
    # this is required to maintain readability
    - path: ^pkg/utils/permutil/name_terms.go$
      linters:
        - golint
        - stylecheck
      text: should not use dot imports