linters:
  disable-all: true
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
    - bodyclose
    - golint
    - stylecheck
    - gosec
    - interfacer
    - unconvert
    - dupl
    - goconst
    - gocyclo
    - gocognit
    - gofmt
    - goimports
    - maligned
    - depguard
    - misspell
    - lll
    - unparam
    - dogsled
    - prealloc
    - gocritic
    - gochecknoinits
    - funlen

issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - gocyclo
        - gocognit
        - errcheck
        - dupl
        - gosec
        - goconst
        - funlen
    # test utilities might not fulfill all conventions, as they are just used
    # for testing
    - path: test_util\.go$
      linters:
        - golint
        - unparam
    # restriction functions tend to get long/complex
    - path: ^pkg/impl/restriction/
      linters:
        - funlen
        - gocognit
    # there would be no point in splitting this up
    - path: ^pkg/utils/embedutil/builder.go$
      linters:
        - funlen
      text: ^Function 'Build' is too long \(\d+ > \d+\)$
    # this is required to maintain readability
    - path: ^pkg/utils/locutil/permission_terms.go$
      linters:
        - golint
        - stylecheck
      text: should not use dot imports