name: Lint

on: [pull_request]

jobs:
  review:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          path: ./go/src/github.com/${{ github.repository }}
      - name: golangci-lint
        uses: reviewdog/action-golangci-lint@v1
        with:
          reporter: github-pr-review
          
